#Sam Pupke
#CPSC 1070
#11 Nov 2023

compile:
	#hashtag spam is for separating previous compiles and other terminal messages from current compile to make it easier to read, hopefully won't forget to remove.
	################################################################################################################################################################################################################################
	g++ Queue.cpp -c -Wall
	g++ Cipher.cpp -c -Wall
	g++ Project3.cpp Queue.o Cipher.o -o "project3.out" -Wall

run:
	./project3.out

clean:
	rm *.out

edit:
	emacs Project3.cpp

queue:
	emacs Queue.h Queue.cpp

cipher:
	emacs Cipher.h Cipher.cpp

file:
	vi makefile

#i would like to commend myself for having the dumbest yet best makefiles
