#Sam Pupke
#CPSC 1071 010: E3 A++
#Dec 4 2023
compile:
	echo #################################################################################################################################
	gcc LinkedList.c -c -Wall
	gcc driver.c LinkedList.o -Wall 

run:
	./a.out

clean:
	rm *.o
	rm *.out

file:
	vi makefile

edit:
	emacs LinkedList.h LinkedList.c

driver:
	emacs driver.c

node:
	emacs Node.h

work:
	emacs Node.h LinkedList.c
